os: linux
dist: bionic
language: python
python:
  - "3.7"
cache: pip
stages:
  - name: ansible-lint
    if: type == pull_request
install:
  - pip install ansible==2.10
  - pip install ansible-lint

jobs:
  include:
    - stage: ansible-lint
      name: "Linting stage"
      script: |
        for role in $(ls tools/roles_lists) ; do ./tools/get-roles.sh $role ; done
        ansible-lint --exclude tools --exclude roles
