## Example mapping file
# have following format:
# changed_file_name:
#   run-file-for-changed-conf.yml:
#     - tag-for-run-one

mappings:
  scrape_configs_*.yml:
    playbooks/monitoring/run-vmagent.yml: []

  users_vault.yml:
    playbooks/configuration/run-server-common.yml:
      - users
      - ssh_keys

  users.yml:
    playbooks/configuration/run-server-common.yml:
      - users
      - ssh_keys

  nginx.yml:
    playbooks/services/run-nginx.yml: []

  tls.yml:
    playbooks/services/run-services.yml: []
